services:
  nats-server:
    container_name: nats-server
    image: nats:2.10-alpine
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"   # client
      - "6222:6222"   # cluster
      - "8222:8222"   # monitoring
    volumes:
      - nats-server-data:/data
    depends_on:
      - postgres

  nats-ui:
    container_name: nats-ui
    image: ghcr.io/nats-nui/nui:latest
    ports:
      - "31311:31311"
    environment:
      - NATS_URL=nats://nats-server:4222
    volumes:
      - nats-ui-data:/db
    depends_on:
      - nats-server

  postgres:
    container_name: riskr-db
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: riskr
      POSTGRES_USER: riskr
      POSTGRES_DB: riskr
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  nats-server-data: {}
  nats-ui-data: {}
  pg-data: {}
