version: "3.9"
services:
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"   # client
      - "6222:6222"   # cluster (unused single node)
      - "8222:8222"   # monitoring
    volumes:
      - nats-data:/data

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: riskr
      POSTGRES_USER: riskr
      POSTGRES_DB: riskr
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  nats-data: {}
  pg-data: {}
