apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus            # keep in sync with the dashboard targets
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false