# Global riskr configuration (edit as needed)
log_level: info
nats:
  urls: ["nats://localhost:4222"]
  ensure_streams: true
http:
  listen_addr: ":8080"
  read_timeout_ms: 5000
  write_timeout_ms: 5000
policy:
  # initial policy file path (used by gateway/streamer on startup)
  # if path is relative, it should be relative to this config file
  file: "./policy.example.yaml"
sanctions:
  file: "./sanctions.example.txt"
assets:
  # static USD conversion factors (MVP); use float or string
  USDC: 1.00
  USDT: 1.00
  WETH: 3000.00
  BTC: 65000.00
latency_budget_ms: 100
