# riskr Policy Set (v2025-07-17.1)
# Five initial rules: OFAC, Jurisdiction, KYC Tier Cap, Daily Volume, Structuring
policy_version: "2025-07-17.1"

params:
  # thresholds used by certain rules
  kyc_tier_caps_usd:
    L0: 1000
    L1: 5000
    L2: 100000
  daily_volume_limit_usd: 50000
  structuring_small_usd: 10000
  structuring_small_count: 5

rules:
  - id: R1_OFAC_ADDR
    type: ofac_addr
    action: REJECT_FATAL

  - id: R2_JURISDICTION_BLOCK
    type: jurisdiction_block
    action: REJECT_FATAL
    blocked_countries: ["IR","KP","SY","RU"]

  - id: R3_KYC_TIER_TX_CAP
    type: kyc_tier_tx_cap
    action: HOLD_AUTO

  - id: R4_DAILY_USD_VOLUME
    type: daily_usd_volume
    action: HOLD_AUTO

  - id: R5_STRUCTURING_SMALL_TX
    type: structuring_small_tx
    action: REVIEW

signature: "UNSIGNED-MVP"