{
 "title": "NATS Server & JetStream",
 "tags": [
  "nats",
  "jetstream"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gnatsd_varz_connections" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    { "expr": "gnatsd_varz_subscriptions" }
   ]
  },
  {
   "title": "JS Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    { "expr": "jetstream_server_total_streams" }
   ]
  },
  {
   "title": "JS Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "jetstream_server_total_consumers"
    }
   ]
  },
  {
   "title": "Message Throughput (per s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "rate(gnatsd_varz_in_msgs[1m])", "legendFormat": "In msgs" },
    { "expr": "rate(gnatsd_varz_out_msgs[1m])", "legendFormat": "Out msgs" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "gnatsd_varz_mem", "legendFormat": "bytes" }
   ]
  }
 ]
}